### ISSUE TITLE
newDivchild is underfined, Line 530, possible typo?

### ISSUE THREAD

**Issue by joemcloE** [qodesmith/typer#10]
Running

```typer('.class')
        .line('<div>Test</div>')
        .pause(1000)
        .back('all')
        .line(<div>Test2</div>)```

Throws an exception on line 530
```        if (child.childNodes.length) num += countVoids(q.newDivchild.childNodes);
```
Cannot read property 'childNodes' of undefined

I suspect newDivchild is a typo.

**Comment by qodesmith** [comment]
Thank's for finding this! This was a bit more than a typo, but yea. `q.newDivchild.childNodes` was nowhere near what it needed to be. It needed to be `child`. Must have blanked out when I originally wrote it.
