### ISSUE TITLE
Request: Allow DOM element references to be directly passed into Typer

### ISSUE THREAD

**Issue by samthecodingman** [qodesmith/typer#11]
Firstly, great work you've done here and what a fantastic demo.

Now to the gritty stuff. I'd like to be able to pass in a DOM Element straight into Typer. Once I figure this out in a clean way rather than just deleting [line 37](https://github.com/qodesmith/typer/blob/master/typer.js#L37), I'll chuck together a PR if I get the chance. At the moment it's just a duct-tape style fix.

Why would I (and potentially others) need this? Well I am currently working with Web Components and the Polymer framework, which makes a real mess of class names and element IDs, meaning that the use of CSS selectors becomes a pain, so I'm just passing the element handle in using the web components helper methods. (Which in the case of Polymer is `this.$.typer` or `this.$$.typer` for an element with the id `typer`.

Related Information:
http://stackoverflow.com/q/384286/3068190

**Comment by qodesmith** [comment]
It was just a matter of time before this was requested :) I thought about this when I first created the library - wether to use a string selector and let the library do the selecting or have the user provide the DOM element itself. I'll see how I can make this optional. Like you said, it may be more than just dealing with line 37. Off the top, I'm not sure where else in the code things might need to change. If you end up getting a PR together, great. If not, when I get some down time I'll implement it myself. I agree it would be a welcomed option.

**Comment by qodesmith** [comment]
@samthecodingman Ok my friend, the changes have been made. Let me know if you find any issues with it. Thanks!
