### ISSUE TITLE
back('all') doesn't deal with HTML elements

### ISSUE THREAD

**Issue by samthecodingman** [qodesmith/typer#12]
The `.back('all')` functionality calculates the number of characters from `newDiv.textContent`, and then removes content by overwriting `newDiv.textContent`. This does not appear to correctly deal with `<em>`, `<span>` and `<strong>` elements.

MWE:
```
typer('#typed')
	.line('Hello I am <em>Sam</em>')
	.back('all')
```

**Comment by qodesmith** [comment]
Confirmed. I'll get a fix going soon. I appreciate your findings!

**Comment by qodesmith** [comment]
@samthecodingman Fixed!
