### ISSUE TITLE
Possible to type instantly?

### ISSUE THREAD

**Issue by morinted** [qodesmith/typer#13]
I'd like to be able to set a type speed of 0, where the whole word is applied instantly, as if to simulate a paste. Thoughts?

**Comment by qodesmith** [comment]
@morinted Yessir! Giving the `.line` or `.continue` methods an array will do exactly what you want:
```javascript
typer('.selector')
  .line(['This whole sentence will be put on the screen at once just like a copy/paste'])
```

**Comment by morinted** [comment]
Sorry for not reading the docs closely enough!

**Comment by morinted** [comment]
Is it possible to do something similar with back? 1ms still has an
animation time. I'd like to simulate Ctrl+backspace, for example.
Essentially removing a certain number of letters instantly.

**Comment by qodesmith** [comment]
Right now its only possible to erase the whole line at once: `.back('empty')`. Perhaps it might be worth it to add a 2nd argument in conjunction with `.back('empty', 10)` that will erase that many characters at once.

**Comment by qodesmith** [comment]
On second thought, that might be confusing since the API already allows other scenarios with `.back` to have a 2nd argument which is the speed. I'll think a bit more through it.

**Comment by morinted** [comment]
Would speed 0 work as a switch? That is what I intuitively tried initially.

**Comment by qodesmith** [comment]
The library prevents 0 speeds and will bump it up to 1. But if I'm understanding you correctly, you don't want to necessarily empty the whole line at once (which Typer can do already) rather you want to be able to erase a set amount of characters at once, correct?

**Comment by morinted** [comment]
That is correct.

How about mirroring the line API, back([3, 4]) to remove three then four
letters instantly, separated by speed?

**Comment by qodesmith** [comment]
Seems like something that can be done. Right now I'm working on another feature, to humanize the typing speed. I'll circle back around to this soon.
