### ISSUE TITLE
Listen/emit sample HTML?

### ISSUE THREAD

**Issue by whatnameshouldi** [qodesmith/typer#14]
Hello,

I am really new to JS (pure rookie) but I am trying to use typer for a small project (a simple HTML page with typewriting effect). So far I've been loving it and I've been able to call most of the basic functions.
The thing is that I don't seem able to use the listen/emit methods.
I'm trying to emit from a #id1 and listen from a #id2 (each in different p blocks) but with no luck. Probably I am making a dumb mistake but I am not sure which. 
Maybe you could provide a short full-code sample of these functions?
Thank you for your great work!

**Comment by qodesmith** [comment]
Hey @whatnameshouldi. Glad you're liking the library so far.

Here's how to [emit](https://github.com/qodesmith/typer#emit) a `boom` event from `#id1`:
```javascript
.emit('boom', '#id1')
```
It will broadcast a custom event with the name `boom` _from_ your `#id1` paragraph element. You can use any event name you like, this example is just showing an arbitrary name for the sake of explanation.

Here's how to [listen](https://github.com/qodesmith/typer#listen) to a `click` event from `#id1`:
```javascript
.listen('click', '#id2')
```
Again, the name of the event is whatever you specifically need to listen to. Keep in mind that when using the [listen](https://github.com/qodesmith/typer#listen) method, Typer will stop typing and wait for that event to fire before proceeding.

I hope this helped. If this doesn't address your issue, post some code so I can understand how you're using it and possibly further diagnose what's going on.

**Comment by whatnameshouldi** [comment]
Thank you for your answer. I meant the use of these methods in context (as in surrounded with --dummy-- code). I kept trying and got as far as this by running nested functions. I'll leave it here in case it helps someone.

`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
 <link rel="stylesheet" href="styles.css">
<script src="typer.js"></script>

<script>
function myFunction1() {
	let element = document.querySelector("#test_id3");
    typer (element)
 .line("This element fired a tick")
 .emit ("test");
 }
</script>

<script>
function myFunction2() {
	let element = document.querySelector("#test_id4");
    typer (element)
 .line("This element was fired after a tick")
 
 }
</script>

 <title>Button test</title>

</head>
<body>
<h1>Button test</h1>
<button type="button" onclick="myFunction1()">Emit</button>

<p id="test_id2"></p>
<p id="test_id3"></p>
<p id="test_id4"></p>
<p id="test_id5"></p>
<p id="test_id6"></p>

<script>
	let element = document.querySelector("#test_id2");
 typer(element)
 .line("Click to fire")
 .listen("test")
  .line("Tick")
  .run (function() {myFunction2() });
     	</script>
 
 </body>`

I am not sure if it is the "right thing" to do it. I want to use typer in different parts of the DOM (I think it is called like that) such as a side-bar, footer and p blocks (with identifiers), but I was not sure how to change the "element" target mid-function, and adding another another script to the body didn't work (that is why I made it new functions that I run back and forth from the main script).

The examples provided don't use it like that (or I didn't see any that did something similar). As I said, I am quite new to JS so I'm mostly guessing, any help is really appreciated (even if it may seem obvious :D ).

**Comment by qodesmith** [comment]
@whatnameshouldi Ok, I see what you need. A concrete example. First, let me say that you were almost there with your own code. In order to see `emit` _and_ `listen` working together, you will need **more than one Typer** running on the page, which you attempted in your code. Great! Here's a very small example that uses your own html structure, so running this on your page would work (I'm using id's 5 & 6 since they are unused in the code you pasted:

```javascript
typer('#id5')
  .line('This is a test sentence in #id5.')
  .pause(1000)
  .line('Nothing will type in #id6 until this Typer is finished.')
  .pause(1000)
  .line('About to fire the `emit` method')
  .continue('...', 150)
  .line('NOW!')
  .emit('some-custom-event-name');


typer('#id6')
  .line()
  .listen('some-custom-event-name')
  .continue(`I heard the 1st Typer's event! Success!`);
```
