### ISSUE TITLE
stop and play typer

### ISSUE THREAD

**Issue by ne-u** [qodesmith/typer#15]
hello, great library, it works very fluid :)
just a question, is it possible to stop and play typer or multiple typer with a event listener (like a 'mouseenter') from an element typed out by the library?
and what is the right function for julienne fries? :)

**Comment by qodesmith** [comment]
Hey @ne-u. While the julienne fries might have to wait, I think I can help you out with the other stuff ;) I have two suggestions to accomplish your task...

### 1 - Delegated Event Listener
Prior to running typer, you could have the `mouseenter` event set up on the body, delegated to the element that you _will_ create with Typer. An example:

```javascript
// Add a delegated event listener.
document.body.addEventListener('mouseenter', function(e) {
  // Delegate the event to the `example` class.
  if (e.target.className === 'example') {
    // Do something here.
  }
});

// This Typer will wait patiently for the `mouseenter` event to fire off the
// element with a class name of `example`. Once it hears that event, it will type.
typer('body')
  .listen('mouseenter', '.example')
  .line('I heard the `mouseenter` event!');

// This Typer will create the element with a class name of `example`.
typer('body')
  .line('<div class="example">Move your mouse over me!</div>');
```

### 2 - Using the 'Run' Method
You can have Typer do _all_ the work, including setting up the event listener.

```javascript
// This Typer will wait patiently for the `mouseenter` event to fire off the
// element with a class name of `example`. Once it hears that event, it will type.
typer('body')
  .listen('mouseenter', '.example')
  .line('I heard the `mouseenter` event!');

// This Typer will create the element with a class name of `example`
// and also afterwards create the event listener.
typer('body')
  .line('<div class="example">Move your mouse over me!</div>')
  .run(function() {
    document.querySelector('.example').addEventListener('mouseenter', function(e) {
      // Do something here.
    });
  });
```

**Comment by ne-u** [comment]
wow, great reply!
maybe i explained my need in wrong way :(
i wrote a codepen (https://codepen.io/ne-u/pen/QMmVdr) to avoid misunderstandings, thxxx

**Comment by qodesmith** [comment]
I think I get what you want. You want the Typer's to pause when you mouse over the link, then when you leave the link, you want them to stop again, correct? If that's the case, then no, out of the box you can't do this with Typer.

I played around in a codepen to try to simulate what you want to do, but without a _lot_ of hackery, it really isn't possible. Perhaps this is a good case for individual Typer's to be able to be controlled (paused / continued) remotely (i.e. outside the scope of its internal API). I'll consider adding this as a feature.

In the meantime, check out the [Kill Switch](https://github.com/qodesmith/typer#kill-switch) built into the library which will effectively kill all Typer's on the page. Maybe you can come up with something temporary that utilizes that.
