### ISSUE TITLE
Start again

### ISSUE THREAD

**Issue by jpcontrerasv** [qodesmith/typer#16]
Great great plugin, but... how can you start it over again when is finished? Simple as that.

**Comment by qodesmith** [comment]
Here's an example:

```javascript
function neverStop() {
  typer('.some-element')
    .line('This is the 1st line.')
    .pause(1000)
    .back('all', 10)
    .continue('Now we begin again...')
    .pause(1000)
    .back('all', 10)
    .run(function(el) {
      el.innerHTML = '';
      document.body.dispatchEvent(new Event('killTyper'));
      setTimeout(() => neverStop(), 10);
    });
}
```

**Comment by jpcontrerasv** [comment]
thanks! perfect

**Comment by kojuka** [comment]
Thanks for this.  Can I suggest we add a `restart`, `replay`, or `loop` method to typer to do this?

It would be great if it looked something like this:

```
typer('.some-element')
    .line('This is the 1st line.')
    .pause(1000)
    .back('all', 10)
    .continue('Now we begin again...')
    .pause(1000)
    .back('all', 10)
    .replay()
```

**Comment by qodesmith** [comment]
@kojuka That's actually a pretty cool idea. Let me toy around with this and see what happens.

**Comment by Grill3dCheese** [comment]
Hello! To @kojuka point - was wondering if restart, replay or loop were ever implemented? I tried using the example you've provided to get typer to loop but oddly it isn't working for me.

**Comment by qodesmith** [comment]
@Grill3dCheese Forgot all about it. Started working on it tonight. I've got it working, but I'm ironing out some of the nuances of how it works.

**Comment by Grill3dCheese** [comment]
@qodesmith Hey! Thanks for getting back to me :) so I'm still pretty new at JS, my guess is I'm doing something wrong. Here is the code I'm using:

		typer('.brand-heading')
			.cursor({ color: '#e1a87a' })
			.line('Intuitive', { min: 20, max: 350 })
			.pause(500)
			.back(-1, 200)
			.continue('nnovative', { min: 30, max: 350 })
			.pause()
			.back(-1, 200)
			.continue('ntriguing', { min: 30, max: 350 })
			.pause()
			.back(-1, 150)
			.continue('mpressive', { min: 30, max: 350 })
			.pause()
			.back(-1, 200)
			.continue('nspiring', { min: 30, max: 350 }) 

I tried wrapping this in the code provided like so:

		function neverStop() {
		typer('.brand-heading')
			.cursor({ color: '#e1a87a' })
			.line('Intuitive', { min: 20, max: 350 })
			.pause(500)
			.back(-1, 200)
			.continue('nnovative', { min: 30, max: 350 })
			.pause()
			.back(-1, 200)
			.continue('ntriguing', { min: 30, max: 350 })
			.pause()
			.back(-1, 150)
			.continue('mpressive', { min: 30, max: 350 })
			.pause()
			.back(-1, 200)
			.continue('nspiring', { min: 30, max: 350 })
			.back('all', 10)
			.run(function(el) {
			  el.innerHTML = '';
			  document.body.dispatchEvent(new Event('killTyper'));
			  setTimeout(() => neverStop(), 10);
			});
		}

Sorry for taking your time with this, I'm guessing it's something fairly simple I'm missing. When I wrap it in the neverStop function and reload the page, the typer no longer works. If I revert back to the first block of code, it starts working again.

**Comment by qodesmith** [comment]
@Grill3dCheese That looks right. My guess is you never called `neverStop()` somewhere in your code 😺

**Comment by Grill3dCheese** [comment]
Yep! You’re exactly right that was my issue. Thanks again Aaron, I appreciate it!

**Comment by qodesmith** [comment]
@Grill3dCheese @kojuka There's a new `.repeat` method that handles all this now. Latest version on npm is 5.1.0.
