### ISSUE TITLE
Possible to repeat the typer?

### ISSUE THREAD

**Issue by PatrickRNG** [qodesmith/typer#19]
Is it possible to repeat the typer function, like when it reach the end, it begins again.
I tried wrapping the typer() in a function and at the end do .run(functionName), but it didn't work

**Comment by PatrickRNG** [comment]
I got it to work, at the end using .end(functionName)

**Comment by qodesmith** [comment]
@PatrickRNG Glad you figured it out! Just in case, here was my proposed way to do it: https://github.com/qodesmith/typer/issues/16

**Comment by PatrickRNG** [comment]
Thanks! And great job on that Typer library/plugin
