### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by obewanz** [qodesmith/typer#22]
Given that you have a killTyper event, it would be nice if there were a way to restart the typer from where it left off... I'd settle for "replaying" the message from the beginning too, but short of refreshing the page, I haven't been able to figure out how to 'restart' typer once I used the killTyper event.
My javascript skills are substantially lacking, so maybe there is a better way to do this, but the examples don't really help. ...otherwise, I LOVE this little utility!! :-) :-)
Sorry if my being lacking in javascript is not helpful.

**Comment by qodesmith** [comment]
Hey @obewanz. First, no worries on what your JavaScript level is. We're all learning! I think you bring up an interesting idea - pause/un-pause Typer with an _event_. At the moment, there is no way to do it. But I like this feature so I'll work on implementing it. I'll keep you posted. Thanks for the love!

**Comment by obewanz** [comment]
Hello Aaron,I have a kludgey implementation of a toggle (not exactly what I wanted, but close enough) that kinda does the job on a fan page game tool that I am working on that presents an "[end transmission]" button when the typer starts - and when it ends, it presents a "[replay transmission]" button. I am trying to do a variation where I can insert a pause (in this case after x lines) and at the same time change the button to a "[resume transmission]" state by using the (.listen) method. The data presented is dynamic and I accomplish that by using an include of individual pages (txID_x.php) which contain the actual (typer) content code - sample follows

=================================================================<script>function transmit(){let element = document.querySelector(".comPanel");typer(element) //* 12 lines fill the screen when using - Transmission End - syntax //* 11 lines available before scroll if using a header line //* 75 chars per line when using the UICC - format .line('<span class="type--base">Connecting to Data Warehouse - Please Wait.</span>', 20) .pause(400) .continue('.') .pause(400) .continue('.') .pause(800) .empty() .line('<span class="type--base">[SyRaM Corporation]</span>', 20) .pause(400) .line('<span class="type--small">- Data File: FALCON</span>', 10) .line('<span class="type--small">- Type: Combat Assault Vehicle (Large Chassis)', 10) .line('<span class="type--small">- Role: Battlefield Superiority / Attack', 10) .line('<span class="type--small">- --SUMMARY--</span>', 10) .pause(400) .line('<span class="type--small">- Data Cell </span>', 10) .pause(400) .continue('<span class="type--small">[ E M P T Y ]</span>', 10) .pause(800) .line('<span class="type--small"></span>', 10) .line('<span class="type--small"></span>', 10) .line('<span class="type--small"></span>', 10) .line('<span class="type--small"></span>', 10) .line('<span class="type--small"></span>', 10) //always need this last line as part of msg protocol .line('<span class="type--small">- - - - Transmission End - - - - </span>', 10) .end(function(el){txToggleBtn('btnKill')},true);}</script>=================================================================
This is the code on the calling page (header and unecessary elements, etc omitted):=================================================================<body id="comdisplay" onload="comPanelInit();"><div id="data-panel" class="data-panel"> <div id="comDisplay" class="comPanel">
 </div> <p id="txComBtn" class="cmd-bottom-display"><a href="#" class="type-button type-opaque" id="btnKill" onclick="txToggleBtn(this.id)">[END TRANSMISSION]</a></p></div>
<script type="text/javascript" src="<?=DIR_WS_INCLUDES;?>javascript/typer.js"></script><script>
var txEndOutput = "UICC Channel has been Disconnected";var txBtnReplay = "[REPLAY TRANSMISSION]";document.getElementById("btnKill").addEventListener("click", function(){ var kill = new Event('killTyper'); document.body.dispatchEvent(kill);
 var paragraph = document.getElementById("comDisplay"); var txEnd = document.createTextNode(txEndOutput); paragraph.appendChild(txEnd);});function txToggleBtn(btnId) { if(btnId == 'btnKill'){ var para = document.createElement("p"); para.id = "txComBtn"; para.className = "cmd-bottom-display";
 var webpage = "comdisplay.php?txID=<?=$txID?>"; var aTag = document.createElement('a'); aTag.id = "btnReplay"; aTag.className = "type-button type-opaque"; aTag.setAttribute('href',webpage); aTag.innerHTML = "[REPLAY TRANSMISSION]"; //var node = document.createTextNode(newButton); var node = document.createTextNode(''); para.appendChild(aTag);console.log(para); var element = document.getElementById("data-panel"); var target = document.getElementById("txComBtn");console.log(target); element.replaceChild(para, target); //btn.removeEventListener("click",dispatchEvent(killTyper),true); //btn.removeEventListener("click",killTyper); } //need to add listener to replay typer event}</script><?// plan on using txER_ for error messagesinclude(DIR_FS_APP_INCLUDES.'transmissions/txID_'.$txID.'.php');?><script>function comPanelInit() { var x = document.getElementById("txComBtn");
 if (typeof transmit == 'function') { 
 // safe to use the function x.style.display = "block"; transmit(); } else { x.style.display = "none"; }}
</script></body>=================================================================
You can view my implementation so far at http://cavso.miniaturegameworks.com/desktop/index.php?fid=6
The above link is a shortcut to the page where I am using this script.Functionality (just in case I have broken something while working) - lower right panel simulates an old style CRT display using typer as it's "engine". Clicking on the Falcon model (first model in the select-bin [left column]) will initialize the "com display" using the model specific content. The panel should initialize with a "welcome" message once the page has loaded.
Thanks for the reply and looking into my suggestion for a pause/resume feature. :o)
Cheers!Steve
May The Force Be With You... 

   On Monday, July 30, 2018, 7:25:30 AM CDT, Aaron Cordova <notifications@github.com> wrote: 
 
 
Hey @obewanz. First, no worries on what your JavaScript level is. We're all learning! I think you bring up an interesting idea - pause/un-pause Typer with an event. At the moment, there is no way to do it. But I like this feature so I'll work on implementing it. I'll keep you posted. Thanks for the love!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Suggestion · Issue #22 · qodesmith/typer

Given that you have a killTyper event, it would be nice if there were a way to restart the typer from where it l...
 |

 |

 |

**Comment by obewanz** [comment]
Aaron,Sorry, I forgot something in my last message... 
When I use the empty() method, it seems to force my next line() output on the 2nd line of the "screen" instead of the first... is there something I should do after the use of empty() to make the next line() output on the first line/row? (I have tried using a back('all') and back('empty') - however, both methods leave a blank line above the following line() output.) This behavior can be observed in the welcome message of my project as I empty the screen to output a second page of data (currently just test lines).
Cheers!Steve
May The Force Be With You... 

   On Monday, July 30, 2018, 7:25:30 AM CDT, Aaron Cordova <notifications@github.com> wrote: 
 
 
Hey @obewanz. First, no worries on what your JavaScript level is. We're all learning! I think you bring up an interesting idea - pause/un-pause Typer with an event. At the moment, there is no way to do it. But I like this feature so I'll work on implementing it. I'll keep you posted. Thanks for the love!

**Comment by obewanz** [comment]
Oh dang! I'm sorry, just figured out if I use a continue() for that next line output, it puts it on the topmost line of the display.
Cheers!
May The Force Be With You... 

   On Monday, July 30, 2018, 7:25:30 AM CDT, Aaron Cordova <notifications@github.com> wrote: 
 
 
Hey @obewanz. First, no worries on what your JavaScript level is. We're all learning! I think you bring up an interesting idea - pause/un-pause Typer with an event. At the moment, there is no way to do it. But I like this feature so I'll work on implementing it. I'll keep you posted. Thanks for the love!

**Comment by qodesmith** [comment]
@obewanz I've got an implementation working on the `pause-event` branch. It's a poorly named branch because originally I intended to add this new functionality via an event listener.

The API will contain 2 new methods: `.hault()` and `.resume()`. I'll be adding documentation to the readme, but here's the lowdown:

### .halt()
This will "halt" Typer in it's tracks. It differs from the `pause` method since `pause` is only declared at runtime and cannot be triggered programatically. `halt`, on the other hand, is triggered *after* Typer is already in action. So the user can basically halt the Typer series of event's with this method. The only catch is it will do nothing if Typer is in "pause" mode or "listen" mode.

### .resume()
Calling this method is how you will resume Typer from previously having called `.halt`.

I'll let you know once it's all ready. Need to write a few tests and add to the documentation.

**Comment by qodesmith** [comment]
@obewanz And there you have it, sir. Typer v4.1.0 - now including the `halt` and `resume` methods :)

**Comment by obewanz** [comment]
Do I have to install the typer.less code to run now? It appears the typer.min.js and the typer.js do not contain the same core code implementation.

**Comment by qodesmith** [comment]
You don't use the `src/typer.js` file, rather, the `typer.min.js` file found in the root. And if you want to see the cursor, you include the `typer.css` file as before.

**Comment by qodesmith** [comment]
So basically nothing has changed except that the `typer.js` file in the root is gone. It wasn't meant to be used anyway since it's newer ES6 syntax would break in older browsers.
