### ISSUE TITLE
https://github.com/qodesmith/typer.git

### ISSUE THREAD

**Issue by cainbyrne** [qodesmith/typer#30]
Hi Team,

Don’t you just hate it when someone includes your open source project, only to run some scanning tools and come back with issues?  Yea we do too.

So we’ve been running lots of security scans on open source projects, including yours, through some automation we built.  Don’t worry, it took less than a few minutes to run the scans and auto-generate the report.

Wasn’t sure how to send it to you, so we’ve stuck them up at https://source-security.co.uk/2ebe2caf-2a27-4f3c-b152-742de666bafa/ so you can see if anything needs handled.  Feel free to re-run the security scanning anytime you like, it’s free for open source.

Best of luck,

Cain

**Comment by qodesmith** [comment]
**** PLEASE, NOBODY CLICK THE LINK ABOVE. ****

I don't know what that link leads to, if it's a phishing site, or what. This user has been blocked and I'm closing this issue immediately.
