### ISSUE TITLE
Cursor is does not work...?

### ISSUE THREAD

**Issue by FxllenCode** [qodesmith/typer#36]
Hi, first, thanks for making this great resource, it works like a charm!

I'm having issues with cursor's however. I'm currently using a _very_ basic implementation of this resource. My JS code is minimal for handling typer.js. However, I seem to be having issues with the cursor popping up. 

```js

typer('.typewriter', 150)
  .line('FxllenCode')
  .cursor({ block: true, blink: 'hard', color: 'black' })

```

This is all I'm using for typer.js. I've gotten it to type it out in typewriter style, but the cursor does not appear:

![icDGrHXW6d](https://user-images.githubusercontent.com/40151425/116642412-cd27c680-a93c-11eb-8c4b-933c25fdfb36.gif)

If it helps, I am using the CDN version of typer.js.

Help appreciated! Thanks!

**Comment by qodesmith** [comment]
Hey, did you forget to include the css file in your project?

**Comment by FxllenCode** [comment]
Hi, yes, apologies for being vague, this is just the snippet. The actual typing animation works fine but the cursor does not appear.

**Comment by qodesmith** [comment]
What I'm saying is, perhaps the cursor isn't showing because you didn't import Typer.js's css file. You need both the JS and the css.

**Comment by FxllenCode** [comment]
I imported both the CSS and the JS file via the CDN provided in the description.

**Comment by FxllenCode** [comment]
@qodesmith looks like I found the issue, the CSS'S CDN does not work:

https://unpkg.com/typer-js@5.5.2/typer.css

Might want to look into that! :grin:

**Comment by qodesmith** [comment]
Ahhh, good catch! This is the correct link:
https://unpkg.com/typer-js@5.5.2/dist/typer.min.css
