### ISSUE TITLE
_typerJs.default.cursor is not a function

### ISSUE THREAD

**Issue by ghost** [qodesmith/typer#38]
I have installed `typer-js` with npm for my project but when I try to use the `.cursor()` method, it runs into an error saying:
```
_typerJs.default.cursor is not a function
```

This is the code in my `index.js` file:
```
import "./styles.css";
import typer from "typer-js";

typer.cursor({ block: true, blink: "smooth", color: "hsl(235, 10%, 95%)" });

typer(".test").line("Typer JS is awesome (ig)");

typer("#commands", { min: 40, max: 60 })
  .line("> date")
  .pause(500)
  .line(`${new Date().toDateString()}`);
```

**Comment by qodesmith** [comment]
This is legit. `typer.cursor(...)` isn't a function, but `typer('.test').cursor(...)` is.

`typer` is a function which returns an object. `cursor` is a method on that returned object.
