### ISSUE TITLE
working with text nodes

### ISSUE THREAD

**Issue by ohadnav** [qodesmith/typer#6]
may deal with issues where an html tag has special characters within it. Consider the case where typing` <a onclick='if(Date.now() > yesterday) doX()'>.`

**Comment by qodesmith** [comment]
Good point. I'm working on revamping the way typer parses. Stay tuned...

**Comment by qodesmith** [comment]
@ohadnav Just pushed version 2.3.0. _**Completely**_ re-worked the html parsing. That means that the `.back` method and typing in general (`.line` or `.continue`) process things way more efficiently and will handle the case you mentioned above. Thanks for the inspiration to re-work it all!
