### ISSUE TITLE
Error on Firefox

### ISSUE THREAD

**Issue by rhinogroup** [qodesmith/typer#9]
**_SecurityError: The operation is insecure.
Firefox 51.0.1
addStyle /scripts/typer.js:204:7
typer/typerObj.cursor /scripts/typer.js:63:28
	<anónimo>_**

Works as expected in Chrome.
`
<script type='text/javascript' src='/scripts/typer.js'></script><br>
<script type='text/javascript'><br>
typer('#container')<br>
	.cursor({block: true, blink: 'hard', color: 'lime'})<br>
	.line('<span style="color:lime; font-size:1em;">blahblah</span>',300)<br>
	.back(4,300)<br>
	.continue('<span style="color:lime; font-size:1em;">blahblahblahblah</span>',300)<br>
	.pause(10000)<br>
	.empty()<br>
	.continue('<span style="color:lime; font-size:1em;">blahblah</span>',300)<br>
	.back(5,500)<br>
	.pause(2000)<br>
	.continue('<span style="color:lime; font-size:1em;">blahblah</span>',300)<br>
	.pause(10000)<br>
	.empty()<br>
	.continue('<span style="color:lime; font-size:1em;">blahblahblahblahblahblah blahblah</span>',300)<br>
	.pause(10000)<br>
	.empty()<br>
	.cursor({block: true, blink: 'hard', color: '#ffcc00'})<br>
	.continue('blahblahblahblahblahblah v blahblah',true)<br>
	.pause(1000)<br>
	.line('blahblah')<br>
	.pause(1000)<br>
	.continue(' blahblah')<br>
	.pause(1000)<br>
	.line('blahblah')<br>
	.pause(1000)<br>
	.continue(' blahblah')<br>
	.pause(1000)<br>
	.line('blahblah')<br>
	.pause(1000)<br>
	.continue(' blahblah')<br>
	.pause(2000)<br>
	.line('blahblah')<br>
	.pause(1000)<br>
	.line('blahblah')<br>
	.pause(5000)<br>
	.empty()<br>
	.end()<br>
};<br>
</script>`<br>

Sorry about all the edits, trying to format it for easier reading.

**Comment by qodesmith** [comment]
Looking into this now...

**Comment by rhinogroup** [comment]
Thank you so much sir.

**Comment by qodesmith** [comment]
@rhinogroup Thanks for finding this bug! Just pushed a fix. Now Typer is adding its own stylesheets to the `<head>` in certain situations and will clean up after itself in the `.end()` method.

**Comment by rhinogroup** [comment]
You are absolutely awesome man, thank you so much for this!
